### ISSUE TITLE
Cannot run MegaQC - no such table: uploads

### ISSUE THREAD

**Issue by ewels** [ewels/MegaQC#137]
Moved from an email to an issue:

---

Dear Phil,

I was trying to use MegaQC to combine different MultiQC outputs.
First I tried to test the package following the instructions here: https://github.com/ewels/MegaQC/blob/master/docs/installation/installation-testing.md
But looking at all error messages (FYI included here in the e-mail), it seemed to me that rather the server was down and I should wait until it is back online. 
Could it be that there is an issue with the webserver at the moment? 

Best,
Andries

FYI: the error messages

After `initdb`:

```
This is MegaQC v0.2.0

/usr/local/lib/python3.6/site-packages/megaqc/utils/settings.py:47: YAMLLoadWarning:

calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.

 * Environment: test
 * Database type: sqlite
 * Database path: sqlite:////tmp/tmpe9bpgbsm/megaqc.db
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running stamp_revision  -> 4515f66f3690
Initialized the database.
```

after git cloning and the for-loop:
The program is indeed looping:

```
This is MegaQC v0.2.0

/usr/local/lib/python3.6/site-packages/megaqc/utils/settings.py:47: YAMLLoadWarning:

calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.

 * Environment: test
 * Database type: sqlite
 * Database path: sqlite:////tmp/tmpy71hd_ya/megaqc.db
Error - MultiQC megaqc_url not set.
```

And when starting megaqc run and navigating to http://127.0.0.1:5000/ 
which seems to be unavailable and raising:

```python
Job "job1 (trigger: interval[0:00:30], next run at: 2020-10-08 17:14:27 CEST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: uploads

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/usr/local/lib/python3.6/site-packages/megaqc/scheduler.py", line 32, in upload_reports_job
    db.session.query(Upload).filter(Upload.status == "NOT TREATED").all()
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/query.py", line 3346, in all
    return list(self)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/query.py", line 3508, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/query.py", line 3533, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
    distilled_params,
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: uploads
[SQL: SELECT uploads.upload_id AS uploads_upload_id, uploads.status AS uploads_status, uploads.path AS uploads_path, uploads.message AS uploads_message, uploads.created_at AS uploads_created_at, uploads.modified_at AS uploads_modified_at, uploads.user_id AS uploads_user_id
FROM uploads
WHERE uploads.status = ?]
[parameters: ('NOT TREATED',)]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
Job "job1 (trigger: interval[0:00:30], next run at: 2020-10-08 17:14:57 CEST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: uploads

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/usr/local/lib/python3.6/site-packages/megaqc/scheduler.py", line 32, in upload_reports_job
    db.session.query(Upload).filter(Upload.status == "NOT TREATED").all()
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/query.py", line 3346, in all
    return list(self)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/query.py", line 3508, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/query.py", line 3533, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
    distilled_params,
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: uploads
[SQL: SELECT uploads.upload_id AS uploads_upload_id, uploads.status AS uploads_status, uploads.path AS uploads_path, uploads.message AS uploads_message, uploads.created_at AS uploads_created_at, uploads.modified_at AS uploads_modified_at, uploads.user_id AS uploads_user_id
FROM uploads
WHERE uploads.status = ?]
[parameters: ('NOT TREATED',)]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
Job "job1 (trigger: interval[0:00:30], next run at: 2020-10-08 17:15:27 CEST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: uploads

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/usr/local/lib/python3.6/site-packages/megaqc/scheduler.py", line 32, in upload_reports_job
    db.session.query(Upload).filter(Upload.status == "NOT TREATED").all()
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/query.py", line 3346, in all
    return list(self)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/query.py", line 3508, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/query.py", line 3533, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
    distilled_params,
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: uploads
[SQL: SELECT uploads.upload_id AS uploads_upload_id, uploads.status AS uploads_status, uploads.path AS uploads_path, uploads.message AS uploads_message, uploads.created_at AS uploads_created_at, uploads.modified_at AS uploads_modified_at, uploads.user_id AS uploads_user_id
FROM uploads
WHERE uploads.status = ?]
[parameters: ('NOT TREATED',)]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
```

**Comment by TMiguelT** [comment]
Oh, oops. It seems those test instructions are incomplete. Can you suggest to them that they instead follow the dev instructions, which I suspect are more correct: https://github.com/ewels/MegaQC/blob/master/docs/installation/installation-dev.md. The errors they're hitting: `no such table: uploads` and `Error - MultiQC megaqc_url not set.` are addressed in these instructions.
