### ISSUE TITLE
TypeError: '<' not supported between instances of 'NoneType' and 'float' when trying to compare data

### ISSUE THREAD

**Issue by Zethson** [ewels/MegaQC#156]
**Describe the bug**

```python
Traceback (most recent call last):
  File "/home/zeth/anaconda3/envs/megaqc/lib/python3.9/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/zeth/anaconda3/envs/megaqc/lib/python3.9/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/zeth/anaconda3/envs/megaqc/lib/python3.9/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/zeth/anaconda3/envs/megaqc/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/zeth/anaconda3/envs/megaqc/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/zeth/anaconda3/envs/megaqc/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/zeth/anaconda3/envs/megaqc/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/zeth/anaconda3/envs/megaqc/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/zeth/anaconda3/envs/megaqc/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/zeth/anaconda3/envs/megaqc/lib/python3.9/site-packages/flask_debugtoolbar/__init__.py", line 125, in dispatch_request
    return view_func(**req.view_args)
  File "/home/zeth/PycharmProjects/MegaQC/megaqc/api/views.py", line 54, in user_wrap_function
    return function(
  File "/home/zeth/PycharmProjects/MegaQC/megaqc/api/views.py", line 355, in get_comparison_plot
    html = generate_comparison_plot(
  File "/home/zeth/PycharmProjects/MegaQC/megaqc/api/utils.py", line 1376, in generate_comparison_plot
    plot_names = sorted(
TypeError: '<' not supported between instances of 'NoneType' and 'float'
```

**To Reproduce**

1. Follow https://github.com/ewels/MegaQC/blob/feature/dependency_updates/docs/installation/installation-testing.md
2. Open the comparisons page
3. Select e.g. FastQC % as x-axis and adapter content as y-axis

**Expected behavior**

No errors and a neat plot that I don't even know what it is supposed to look like.

**Comment by TMiguelT** [comment]
This is in the "old" (pre-react, and REST api) part of the code, so it's kind of difficult to understand what's happening here. Generally these errors happen when a certain data point is not present for a certain sample. If you want to just get the gist of what this page is for, try plotting some other metrics that aren't missing.

When you get up to rewriting this you might want to look into removing missing data from the plot API endpoint before returning it. I forgot to mention this earlier, but if you're rewriting one of the pages that has front- and back-end components (like the plot pages), you'll need to rewrite the frontend in React as usual, but also my convention is that you also make a new REST endpoint and schema. e.g. https://github.com/ewels/MegaQC/blob/0e33c644389614d87be34ba4ecf6a400ef4e8057/megaqc/rest_api/views.py#L348-L357

**Comment by Zethson** [comment]
Thanks.

> If you want to just get the gist of what this page is for, try plotting some other metrics that aren't missing.

I could not get any plot done on this page using your data.
Can you?

**Comment by tsnowlan** [comment]
You know, I'm not sure how well this page worked to start off with. I know I had problems getting the non-trend pages working nicely when I first started playing with MegaQC, but didn't pay it too much attention since we were just after the trend functionality.

I think a key part of this one was picking the right fields, though. @ewels do you remember how you had this working?

**Comment by TMiguelT** [comment]
It definitely does work, but the reason it isn't working with my sample dataset is because of the phantom `illumina_universal_adapter` samples. See #142. You should be able to just delete them using the admin interface, but this doesn't seem to work (yet another task!). So... yeah. Yet another reason for a rewrite.

**Comment by Zethson** [comment]
I honestly have not found a report yet where this feature works. I have even tried the example MultiQC reports.

**Comment by apeltzer** [comment]
Confirmed here, also with "real" data unfortunately.

**Comment by ewels** [comment]
Quick fix should be to filter out samples with `None` for either `x` or `y` here: https://github.com/ewels/MegaQC/blob/6a0d9be5b96a6a46f0d9e7b2cdbff81582b4a178/megaqc/api/utils.py#L1362-L1382

Long term we want to rewrite this, but filtering Nones should be a fairly speed fix I think.

NB: We should display a warning above the plot if > 0 samples have been filtered out (print how many were hidden).
