### ISSUE TITLE
Violin Plots

### ISSUE THREAD

**Issue by ewels** [ewels/MegaQC#31]
The Violin Plots dropdown option on the Distributions page doesn't work.

**Comment by Rhinogradentia** [comment]
Maybe this error message helps?

```
deployment-megaqc-1  | [2023-11-28 15:15:06,191] ERROR in app: Exception on /api/get_distribution_plot [POST]
deployment-megaqc-1  | Traceback (most recent call last):
deployment-megaqc-1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
deployment-megaqc-1  |     response = self.full_dispatch_request()
deployment-megaqc-1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
deployment-megaqc-1  |     rv = self.handle_user_exception(e)
deployment-megaqc-1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
deployment-megaqc-1  |     reraise(exc_type, exc_value, tb)
deployment-megaqc-1  |   File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
deployment-megaqc-1  |     raise value
deployment-megaqc-1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
deployment-megaqc-1  |     rv = self.dispatch_request()
deployment-megaqc-1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
deployment-megaqc-1  |     return self.view_functions[rule.endpoint](**req.view_args)
deployment-megaqc-1  |   File "/app/megaqc/api/views.py", line 54, in user_wrap_function
deployment-megaqc-1  |     return function(
deployment-megaqc-1  |   File "/app/megaqc/api/views.py", line 328, in get_distribution_plot
deployment-megaqc-1  |     html = generate_distribution_plot(plot_data, nbins, ptype)
deployment-megaqc-1  |   File "/app/megaqc/api/utils.py", line 1297, in generate_distribution_plot
deployment-megaqc-1  |     figure = ff.create_violin(figs)
deployment-megaqc-1  |   File "/usr/local/lib/python3.8/site-packages/plotly/figure_factory/_violin.py", line 611, in create_violin
deployment-megaqc-1  |     plot_data, plot_xrange = violinplot(
deployment-megaqc-1  |   File "/usr/local/lib/python3.8/site-packages/plotly/figure_factory/_violin.py", line 163, in violinplot
deployment-megaqc-1  |     vals = np.asarray(vals, np.float)
deployment-megaqc-1  |   File "/usr/local/lib/python3.8/site-packages/numpy/core/_asarray.py", line 83, in asarray
deployment-megaqc-1  |     return array(a, dtype, copy=False, order=order)
deployment-megaqc-1  | TypeError: float() argument must be a string or a number, not 'dict'
```
