### ISSUE TITLE
MySQLdb missing in container

### ISSUE THREAD

**Issue by chrispyatt** [ewels/MegaQC#319]
Trying to set up using the docker image but with mysql as the DB - seems to need MySQLdb module within the container but it's not there. Do I need to pass it something else in addition?

```console

$ sudo docker run -v $(pwd):/home -p 80:80 -e MEGAQC_CONFIG="/home/megaqc_config.yaml" ewels/megaqc

Checking for script in /app/prestart.sh
Running script /app/prestart.sh
This is MegaQC v0.3.0

Setting SQLALCHEMY_DBMS to mysql
 * Environment: Prod
 * Database type: mysql
 * Database path: mysql://megaqc:***@127.0.0.1:5432/megaqc
Traceback (most recent call last):
  File "/usr/local/bin/megaqc", line 8, in <module>
    sys.exit(main())
  File "/app/megaqc/cli.py", line 75, in main
    cli()
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/app/megaqc/commands.py", line 147, in initdb
    init_db(current_app.config["SQLALCHEMY_DATABASE_URI"])
  File "/app/megaqc/database.py", line 203, in init_db
    engine = create_engine(url)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/__init__.py", line 500, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 87, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 118, in dbapi
    return __import__("MySQLdb")
ModuleNotFoundError: No module named 'MySQLdb'
Setting SQLALCHEMY_DBMS to mysql
 * Environment: Prod
 * Database type: mysql
 * Database path: mysql://megaqc:***@127.0.0.1:5432/megaqc
Traceback (most recent call last):
  File "/usr/local/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask_migrate/cli.py", line 134, in upgrade
    _upgrade(directory, revision, sql, tag, x_arg)
  File "/usr/local/lib/python3.8/site-packages/flask_migrate/__init__.py", line 96, in wrapped
    f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask_migrate/__init__.py", line 271, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/usr/local/lib/python3.8/site-packages/alembic/command.py", line 298, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.8/site-packages/alembic/script/base.py", line 489, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.8/site-packages/alembic/util/compat.py", line 184, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/megaqc/migrations/env.py", line 92, in <module>
    run_migrations_online()
  File "/app/megaqc/migrations/env.py", line 70, in run_migrations_online
    connectable = engine_from_config(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/__init__.py", line 543, in engine_from_config
    return create_engine(url, **options)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/__init__.py", line 500, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 87, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 118, in dbapi
    return __import__("MySQLdb")
ModuleNotFoundError: No module named 'MySQLdb'

```

**Comment by multimeric** [comment]
Can you post the full traceback of the import error? I assume it's another library that is using SQLAlchemy in a deprecated fashion that needs to be updated.

**Comment by ewels** [comment]
@chrispyatt is there a reason that you need to use MySQL instead of Postgres? I suspect that it'll make your life quite a bit easier to stick with the same setup as others, and if you're running in Docker anyway then it should be fairly equivalent..?

**Comment by apeltzer** [comment]
Was wondering the same too - any reason to not use Postgresql?

**Comment by multimeric** [comment]
Hmm these are a bit confusing.

The first issue is apparently because MySQL needs to know how long the index should be when indexing text columns. So for `user.username` we need to pull out the unique constraint into a [`UniqueConstraint`](https://docs.sqlalchemy.org/en/14/core/constraints.html#sqlalchemy.schema.UniqueConstraint) and then tell MySQL how long the index should be (sigh).

Then for the next issue, `plot_config.data` is currently a `UnicodeText` which should translate to `TEXT` and not `VARCHAR` in MySQL, but that's what's causing the problem here.
https://github.com/ewels/MegaQC/blob/27d6619bb1616614a19e59f9bad41496d53049f7/megaqc/model/models.py#L91

Then the

**Comment by multimeric** [comment]
Closing in favour of #332.
