### ISSUE TITLE
Unable to upload Stats.json - KeyError: 'config_creation_date'

### ISSUE THREAD

**Issue by NMNS93** [ewels/MegaQC#47]
Hi there, 
Installed the latest version of MegaQC without problems (commit  bcdef4f), but was unable to upload my files. `megaqc upload *.json` completes successfully, but the 'pending uploads' section of the application displays the following traceback for each file:

```
Traceback (most recent call last):
  File "/home/nana/Documents/megaqc/py2env/local/lib/python2.7/site-packages/megaqc-0.1.dev0-py2.7.egg/megaqc/scheduler.py", line 49, in upload_reports_job
    ret = handle_report_data(user, data)
  File "/home/nana/Documents/megaqc/py2env/local/lib/python2.7/site-packages/megaqc-0.1.dev0-py2.7.egg/megaqc/api/utils.py", line 72, in handle_report_data
    report_hash = generate_hash(report_data)
  File "/home/nana/Documents/megaqc/py2env/local/lib/python2.7/site-packages/megaqc-0.1.dev0-py2.7.egg/megaqc/api/utils.py", line 39, in generate_hash
    data.pop("config_creation_date")
KeyError: 'config_creation_date'
```

Would it have anything to do with the empty field in `megaqc/utils/config_defaults.yaml`? Appreciate any assistance,
-Nana

**Comment by ewels** [comment]
Hi Nana,

Cool that you're working with MegaQC! Can I be nosy and ask what your plans are for it?

The error you see is due to the very latest change I've been working on - getting the sample dates to be from when the MultiQC report was generated, instead of when it was uploaded (means that the trend plot is useful if uploading old reports).

The traceback looks very much like the bug I was fighting the other day. I was pretty sure that I had fixed that, and now I'm suspicious that I didn't push my changes...! I'm working from home today on a different machine, but will double check tomorrow. Apologies if this is the case! If not, I'll look into it.

Phil

**Comment by NMNS93** [comment]
Hi Phil,

Apologies for the late reply. At Guy's Hospital (London) the genetics lab would like to track our reports in aggregate using MegaQC. I will hopefully have some time this month to put it up on a server again and allow the lab scientists to test it out.


If there are any problems will keep you informed, from my use so far it's a great tool, definitely needed!


Best wishes,

Nana

Nana Mensah
Trainee Clinical Bioinformatician (STP)
Genetics Laboratories| 5th Floor Tower Wing | Guy's Hospital | Great Maze Pond | London | SE1 9RT
Tel: 02071881701
Email: Nana.mensah1@nhs.net<mailto:Nana.mensah1@nhs.net>
________________________________
