### ISSUE TITLE
"Can't determine which FROM clause to join from", and "TypeError: %d format: a number is required, not NoneType"

### ISSUE THREAD

**Issue by TMiguelT** [ewels/MegaQC#74]
I uploaded multiQC data to megaQC, which appears to have been successful (it's visible in `/edit_reports`). However, if I try to create a new plot, I get the following errors in the console:

```
[2019-04-12 04:26:56,533] ERROR in app: Exception on /api/get_report_plot [POST]                                                                                                     
```
```python
Traceback (most recent call last):                                                                                                                                                   
  File "/mnt/data/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app                                                                                             
    response = self.full_dispatch_request()                                                                                                                                          
  File "/mnt/data/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request                                                                                
    rv = self.handle_user_exception(e)                                                                                                                                               
  File "/mnt/data/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception                                                                                
    reraise(exc_type, exc_value, tb)
  File "/mnt/data/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/mnt/data/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/data/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/data/venv/lib/python3.6/site-packages/megaqc/api/views.py", line 33, in user_wrap_function
    return function(*args, **kwargs) # else add "user" to kwargs so it can be used in the request handling
  File "/mnt/data/venv/lib/python3.6/site-packages/megaqc/api/views.py", line 179, in get_report_plot
    html = generate_report_plot(plot_type, sample_names)
  File "/mnt/data/venv/lib/python3.6/site-packages/megaqc/api/utils.py", line 289, in generate_report_plot
    rows = db.session.query(PlotConfig, PlotData, PlotCategory, Sample).join(PlotData).join(PlotCategory).join(Sample).filter(PlotConfig.config_name==plot_type[0],PlotConfig.config_dataset==plot_type[1],Sample.sample_name.in_(sample_names)).all()
  File "/mnt/data/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2235, in join
    from_joinpoint=from_joinpoint,
  File "<string>", line 2, in _join
  File "/mnt/data/venv/lib/python3.6/site-packages/sqlalchemy/orm/base.py", line 220, in generate
    fn(self, *args[1:], **kw)
  File "/mnt/data/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2414, in _join
    left, right, onclause, prop, create_aliases, outerjoin, full
  File "/mnt/data/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2437, in _join_left_to_right
    ) = self._join_determine_implicit_left_side(left, right, onclause)
  File "/mnt/data/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2568, in _join_determine_implicit_left_side
    "Can't determine which FROM clause to join "
sqlalchemy.exc.InvalidRequestError: Can't determine which FROM clause to join from, there are multiple FROMS which can join to this entity. Try adding an explicit ON clause to help
resolve the ambiguity.
```
```
127.0.0.1 - - [12/Apr/2019 04:26:56] "POST /api/get_report_plot HTTP/1.1" 500 -
Error on request:
```
```python
Traceback (most recent call last):
  File "/mnt/data/venv/lib/python3.6/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/mnt/data/venv/lib/python3.6/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/mnt/data/venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/mnt/data/venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/mnt/data/venv/lib/python3.6/site-packages/flask/app.py", line 1748, in handle_exception
    return self.finalize_request(handler(e), from_error_handler=True)
  File "/mnt/data/venv/lib/python3.6/site-packages/megaqc/app.py", line 87, in render_error
    response.status_code = error_code
  File "/mnt/data/venv/lib/python3.6/site-packages/werkzeug/wrappers.py", line 949, in _set_status_code
    self._status = '%d UNKNOWN' % code
TypeError: %d format: a number is required, not NoneType
```

This error occurs when I click a plot type, as shown in this screenshot:
![image](https://user-images.githubusercontent.com/5019367/56012329-5573a880-5d2f-11e9-8460-880c20072b9c.png)

**Comment by skanwal** [comment]
Hi Phil,

I am also getting the similar-ish error, when trying to choose a plot type for samples (as shown in the screenshot attached by Michael above). 

```
Traceback (most recent call last):
  File "/Users/kanwals/miniconda3/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/kanwals/miniconda3/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/kanwals/miniconda3/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/kanwals/miniconda3/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/kanwals/miniconda3/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/kanwals/miniconda3/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/kanwals/miniconda3/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/kanwals/miniconda3/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/kanwals/miniconda3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/kanwals/miniconda3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/kanwals/miniconda3/lib/python3.6/site-packages/megaqc/api/views.py", line 33, in user_wrap_function
    return function(*args, **kwargs) # else add "user" to kwargs so it can be used in the request handling
  File "/Users/kanwals/miniconda3/lib/python3.6/site-packages/megaqc/api/views.py", line 179, in get_report_plot
    html = generate_report_plot(plot_type, sample_names)
  File "/Users/kanwals/miniconda3/lib/python3.6/site-packages/megaqc/api/utils.py", line 289, in generate_report_plot
    rows = db.session.query(PlotConfig, PlotData, PlotCategory, Sample).join(PlotData).join(PlotCategory).join(Sample).filter(PlotConfig.config_name==plot_type[0],PlotConfig.config_dataset==plot_type[1],Sample.sample_name.in_(sample_names)).all()
  File "/Users/kanwals/miniconda3/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2235, in join
    from_joinpoint=from_joinpoint,
  File "<string>", line 2, in _join

  File "/Users/kanwals/miniconda3/lib/python3.6/site-packages/sqlalchemy/orm/base.py", line 220, in generate
    fn(self, *args[1:], **kw)
  File "/Users/kanwals/miniconda3/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2414, in _join
    left, right, onclause, prop, create_aliases, outerjoin, full
  File "/Users/kanwals/miniconda3/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2437, in _join_left_to_right
    ) = self._join_determine_implicit_left_side(left, right, onclause)
  File "/Users/kanwals/miniconda3/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2568, in _join_determine_implicit_left_side
    "Can't determine which FROM clause to join "
sqlalchemy.exc.InvalidRequestError: Can't determine which FROM clause to join from, there are multiple FROMS which can join to this entity. Try adding an explicit ON clause to help resolve the ambiguity.
```
Any help will be appreciated.

Regards,
Sehrish
